language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - python3 -m spacy download fr_core_news_sm
  - pip install -e .
addons:
  chrome: stable
  sonarcloud:
    organization: "nohossat-cas-pratique-1"
    token:
      secure: $SONAR_TOKEN
script:
  - pytest
  - sonar-scanner
